### ISSUE TITLE
Creating a <Link> component causes browser crazies

### ISSUE THREAD

**Issue by freshtonic** [ironbay/react-redux-template#5]
Commit that reproduces the issue:

https://github.com/freshtonic/react-redux-template/commit/5323c5da562dfdb39f25f4b29d6bbaa19aaee2d3

I'm new to React and I was having this issue in my own code.  So I tried out react-redux-template only to discover this set up has the same issue. It totally could be me doing something dumb... but please take a look.

**Comment by panathea** [comment]
Didn't try the code but your import should be { Link }, not Link.

**Comment by thdxr** [comment]
Looks like @morinted beat me to it.  Are your problems fixed now?

**Comment by freshtonic** [comment]
@morinted @dax0 yeah kinda embarrassing!  I yak shaved a couple of hours of my life away yesterday because of missing curlies 😛

**Comment by thdxr** [comment]
Haha no worries. Feel free to post any more questions you have
